INSERT INTO Profesor (nombre, paterno, materno, correo) VALUES
('Martin', 'Ordoñez', 'Rosales', 'martinordonez7e1@aragon.unam.mx'),
('Sergio', 'Hernandez', 'Lopez', 'sergiohernandezhel@aragon.unam.mx'),
('Aaron', 'Velasco', 'Agustin', 'aaronvelazcovea@aragon.unam.mx'),
('Gerardo', 'Gonzalez', 'Hernandez', 'gerardogonzalezgoh@aragon.unam.mx'),
('Leobardo', 'Hernandez', 'Audelo', 'leoher34@aragon.unam.mx'),
('Gastaldi', 'Perez', 'Juan', 'juangastaldi9a@aragon.unam.mx'),
('Elizabeth', 'Juarez', 'Robles', 'elizabethjuarezjur@aragon.unam.mx'),
('Jorge Iván', 'Campos', 'Bravo', 'jorgecampos47@aragon.unam.mx'),
('Arturo', 'Rodríguez', 'García', 'arturorodriguez35@aragon.unam.mx'),
('Rafael', 'Gonzalez', 'Betancourt', 'rafaelgonzalezma2@aragon.unam.mx'),
('Miguel Angel', 'Sanchez', 'Hernandez', 'miguelsanchezt32@aragon.unam.mx'),
('Efren', 'lozano', 'Mendez', 'efrenlozanogg2@aragon.unam.mx'),
('Alejandro', 'Suarez', 'Herrera', 'alejandrosuarezsuh@aragon.unam.mx'),
('Jorge Arturo', 'Lopez', 'Hernandez', 'jorgelopez91@aragon.unam.mx'),
('Jonathan', 'Martinez', 'Romero', 'jonathanmartinezky7@aragon.unam.mx'),
('Cesar Francisco', 'German', 'Rosas', 'cesargermanx9@aragon.unam.mx'),
('Omar', 'Mendoza', 'Gonzalez', 'omarmendoza564@aragon.unam.mx'),
('Daniel Fernando', 'Palma', 'Lopez', 'fernandopalmaq6@aragon.unam.mx'),
('Juan Carlos', 'Camacho', 'Alvarez', 'juancamachocaa@aragon.unam.mx'),
('Carlos Alberto', 'Parrales', 'Parrales', 'carlosparralesgi2@aragon.unam.mx'),
('Rafael', 'Gonzales', 'Betancourt', 'rafaglz@aragon.unam.mx'),
('Dzoara Ivette', 'Anaya', 'Manila', 'dzoaraanayaq5@aragon.unam.mx'),
('Martin', 'Romero', 'Ugalde', 'martinromerorou@aragon.unam.mx'),
('Alfredo', 'Mondragon', 'Escobar', 'alfredomondragontg8@aragon.unam.mx'),
('Robeto MIsael', 'Soberanes', 'Jaime', 'misalesoberanesr8@aragon.unam.mx'),
('Jose Francisco', 'Salgado', 'Rodriguez', 'franciscosalgadoi2@aragon.unam.mx'),
('Enrique', 'Garcia', 'Guzman', 'enriquegarcia6u4@aragon.unam.mx'),
('Maria Angelica', 'Feria', 'Victoria', 'angelicaferiaf6@aragon.unam.mx'),
('Juan', 'Gastaldi', 'Perez', 'juangastaldi9a@aragon.unam.mx'),
('Victor Manuel', 'Sanchez', 'Sanchez', 'victorsanchezh0@aragon.unam.mx'),
('Maria Guadalupe', 'Almanzar', 'Vazquez', 'guadalupealmanzar1@aragon.unam.mx'),
('Juan German', 'Valenzuela', 'Ramos', 'germanvalenzuelag3@aragon.unam.mx'),
('Roberto', 'Blanco', 'Bautista', 'robertoblancoir4@aragon.unam.mx'),
('Blanca Pamela', 'Suarez', 'Camacho', 'blancapamela03@aragon.unam.mx'),
('Belen Anaid', 'Alba', 'Villa', 'belenalba749@aragon.unam.mx'),
('Gerardo', 'Gonzalez', 'Hernandez', 'gerardogonzalezgoh@aragon.unam.mx'),
('Juan', 'Gastaldi', 'Perez', 'juangastaldi9a@aragon.unam.mx'),
('Juan Manuel', 'Arellano', 'Orozco', 'juanmanuelioro12@aragon.unam.mx'),
('Esteban', 'Ramirez', 'Lazos', 'estebanralaz03@aragon.unam.mx'),
('Juan Carlos', 'Ramos', 'Marquez', 'jcramos345@aragon.unam.mx'),
('Everardo', 'Solis', 'Alcantar', 'esolis768@aragon.unam.mx'),
('Carlos Alberto', 'Parrales', 'Castaneda', 'caparrales123@aragon.unam.mx'),
('Luis Armando', 'Vieyra', 'Reboyo', 'lavieyra654@aragon.unam.mx'),
('Alfredo', 'Mondragon', 'Escobar', 'amondragon321@aragon.unam.mx'),
('Berenice Itzel', 'Falcon', 'Arellano', 'bfalcon459@aragon.unam.mx'),
('Ma. Del Pilar', 'Garcia', 'Villanueva', 'pdgarcia777@aragon.unam.mx'),
('Ernesto', 'Penalosa', 'Romero', 'epenalosa233@aragon.unam.mx'),
('Jesus Angel', 'Romero', 'Andalon', 'jromero564@aragon.unam.mx'),
('Joel Alfredo', 'Perez', 'Valdes', 'joperez998@aragon.unam.mx'),
('Miguel Angel', 'Sanchez', 'Hernandez', 'masanchez123@aragon.unam.mx'),
('Gabriel', 'Ortiz', 'Cordero', 'gortiz456@aragon.unam.mx'),
('Alejandro', 'Perez', 'Guzman', 'aperez312@aragon.unam.mx'),
('Jorge Luis', 'Candelario', 'Alavez', 'jcandelario876@aragon.unam.mx'),
('Victor Manuel', 'Sanchez', 'Morales', 'vmsanchez257@aragon.unam.mx'),
('Clara Yahaiera', 'Islas', 'Hernandez', 'cyislas392@aragon.unam.mx'),
('Matilde', 'Colunga', 'Vazquez', 'mcolunga678@aragon.unam.mx'),
('Ana Claudia', 'Reyes', 'Cruz', 'acruz321@aragon.unam.mx'),
('Anaid', 'Alba', 'Villa', 'aavilla485@aragon.unam.mx'),
('Arturo', 'Rodriguez', 'Garcia', 'arodgriguez637@aragon.unam.mx'),
('Jorge Ivan', 'Campos', 'Bravo', 'jcampos156@aragon.unam.mx'),
('Blanca Pamela', 'Aburto', 'Camacho', 'paburto222@aragon.unam.mx'),
('Salomon', 'Hernandez', 'Galicia', 'shernandez548@aragon.unam.mx'),
('Efren', 'Guerrero', 'Santamaria', 'eguerrero789@aragon.unam.mx'),
('Cuauhtemoc', 'Chiapa', 'Monroy', 'cchiapa101@aragon.unam.mx'),
('Jose Gil', 'Juarez', 'Palma', 'gjuarez123@aragon.unam.mx'),
('Minerva', 'Segura', 'Rauda', 'msegura775@aragon.unam.mx'),
('Alma Rosa', 'Gutierrez', 'Castillo', 'rgutierrez393@aragon.unam.mx'),
('Blanca Estela', 'Cruz', 'Luevano', 'ecruz302@aragon.unam.mx'),
('Gabriella', 'Piccinelli', 'Bocchi', 'gpiccinelli561@aragon.unam.mx'),
('Abel', 'Verde', 'Cruz', 'avcrc734@aragon.unam.mx'),
('Carlos', 'Oliver', 'Morales', 'colivermorales872@aragon.unam.mx'),
('Fausto', 'Torres', 'Torres', 'ftorres943@aragon.unam.mx'),
('Martin', 'Ordonez', 'Rosales', 'mordonez678@aragon.unam.mx'),
('Martha', 'Chapa', 'Plata', 'mchapa299@aragon.unam.mx'),
('Jesus', 'Hernandez', 'Cabrera', 'jhcabrera512@aragon.unam.mx'),
('Carlos Fernando', 'Ortega', 'Nava', 'cfo120@aragon.unam.mx'),
('Rafael', 'Canto', 'Gallo', 'rcanto876@aragon.unam.mx'),
('Ramon', 'Patino', 'Rodriguez', 'rpatino234@aragon.unam.mx'),
('Gloria Samantha', 'Pelcastre', 'Ramirez', 'gsapelcastre315@aragon.unam.mx'),
('Manuel Alejandro', 'Alvarez', 'Soriano', 'malvarez837@aragon.unam.mx'),
('Moises', 'Cervantes', 'Patino', 'mcervantes102@aragon.unam.mx'),
('Jaime Roberto Misael', 'Soberanes', 'Jaime', 'jsoberanes550@aragon.unam.mx'),
('Norma', 'Reyes', 'Tecontero', 'nreyes167@aragon.unam.mx'),
('Juan Manuel', 'Lopez', 'Carreto', 'jlopez889@aragon.unam.mx'),
('Jorge Carlos', 'Morales', 'Gonzalez', 'jmorales314@aragon.unam.mx'),
('Luis Enrique', 'Gonzalez', 'Ayala', 'legonzalez267@aragon.unam.mx'),
('Jose Luis', 'Ramirez', 'Cruz', 'jramirez408@aragon.unam.mx'),
('Hector', 'Saldana', 'Aldana', 'hsaldana579@aragon.unam.mx'),
('Juan Antonio', 'Villanueva', 'Ortega', 'javillanueva123@aragon.unam.mx'),
('Mariana', 'Verduzco', 'Rodriguez', 'mverduzco542@aragon.unam.mx'),
('Maria Elena', 'Ortiz', 'Jimenez', 'meortiz320@aragon.unam.mx'),
('Esteban', 'Arellano', 'Rivera', 'earellano765@aragon.unam.mx'),
('David Jaime', 'Gonzalez', 'Maxinez', 'djgonzalez849@aragon.unam.mx'),
('Ricardo Arturo', 'Gutierrez', 'Orozco', 'rggutierrez710@aragon.unam.mx'),
('Arcelia', 'Bernal', 'Diaz', 'abernal235@aragon.unam.mx'),
('Maria Gabriela', 'Gonzalez', 'Hernandez', 'mgonzalez541@aragon.unam.mx'),
('Rodolfo', 'Vazquez', 'Morales', 'rvazquez311@aragon.unam.mx'),
('Marcelo', 'Perez', 'Medel', 'mperez436@aragon.unam.mx'),
('Martin', 'Hernandez', 'Hernandez', 'mhhernandez@aragon.unam.mx'),
('Esteban', 'Ayala', 'Pena', 'eayala298@aragon.unam.mx'),
('Juan Manuel', 'Hernandez', 'Contreras', 'jhernandez503@aragon.unam.mx'),
('Jose Antonio', 'Garcia', 'Monroy', 'jgarcia772@aragon.unam.mx'),
('Jose Manuel', 'Quintero', 'Cervantes', 'jqcervantes657@aragon.unam.mx'),
('Arturo', 'Ocampo', 'Alvarez', 'aocampo944@aragon.unam.mx'),
('Alma Lilia', 'Garibay', 'Pedraza', 'algaribay871@aragon.unam.mx'),
('Antonio Gerardo', 'Perez', 'Munoz', 'aperez401@aragon.unam.mx'),
('Gerardo', 'Torres', 'Rodriguez', 'gtorres592@aragon.unam.mx'),
('Ricardo Adolfo', 'Vidal', 'Castro', 'rvidal214@aragon.unam.mx'),
('Judith', 'Ugalde', 'Lopez', 'jugalde648@aragon.unam.mx'),
('Felipe De Jesus', 'Gutierrez', 'Lopez', 'fdlopz888@aragon.unam.mx'),
('Sergio', 'Quiroz', 'Almaraz', 'sqalmaraz549@aragon.unam.mx'),
('Amilcar Amado', 'Monterrosa', 'Escobar', 'aamonterrosa722@aragon.unam.mx'),
('Marco Inti', 'Goytia', 'Herrera', 'mgoytia546@aragon.unam.mx'),
('Benito', 'Zuniga', 'Villegas', 'bzuniga355@aragon.unam.mx'),
('Jose Daniel', 'Castro', 'Diaz', 'jdcastro@aragon.unam.mx'),
('Jose Antonio', 'Avila', 'Garcia', 'javilagarcia470@aragon.unam.mx'),
('Hiram Emmanuel', 'Perez', 'Sanchez', 'hvega711@aragon.unam.mx'),
('Elio', 'Vega', 'Munguia', 'ggalia302@aragon.unam.mx'),
('Gilda', 'Galicia', 'Rangel', 'eneria294@aragon.unam.mx'),
('Erik De Jesus', 'Neria', 'Orozco', 'iflores602@aragon.unam.mx'),
('Imelda De La Luz', 'Flores', 'Diaz', 'jsrodriguez701@aragon.unam.mx'),
('Jose Francisco', 'Salgado', 'Rodriguez', 'agreneponce531@aragon.unam.mx'),
('Alejandro Rene', 'Gonzalez', 'Ponce', 'frcovarrubias589@aragon.unam.mx'),
('Fernando Roberto', 'Covarrubias', 'Rodriguez', 'bcano799@aragon.unam.mx'),
('Berenice', 'Cano', 'Santos', 'rvalenzuelalopez710@aragon.unam.mx'),
('Rodolfo', 'Valenzuela', 'Lopez', 'lhernandezcervantes348@aragon.unam.mx'),
('Liliana', 'Hernandez', 'Cervantes', 'cescondrillas759@aragon.unam.mx'),
('Carlos', 'Escondrillas', 'Maya', 'igradaherta236@aragon.unam.mx'),
('Ivan', 'Grada', 'Huerta', 'epalafox174@aragon.unam.mx'),
('Edgar', 'Morales', 'Palafox', 'jaguilar986@aragon.unam.mx'),
('Jose Francisco', 'Aguilar', 'Hernandez', 'cmvelezangel110@aragon.unam.mx'),
('Carlos Manuel', 'Velez', 'Angel', 'rnavarrodi123@aragon.unam.mx'),
('Ramon', 'Navarro', 'Diaz', 'mriveropicazo795@aragon.unam.mx'),
('Mariela Vianey', 'Rivero', 'Picazo', 'rdavilaperez922@aragon.unam.mx'),
('Rene Adrian', 'Davila', 'Perez', 'renedavilar5@aragon.unam.mx');