INSERT INTO Profesor (id_profesor, nombre, paterno, materno, correo) VALUES
(1, 'Elizabeth', 'Juarez', 'Robles', 'elizabeth34@aragon.unam.mx'),
(2, 'Sergio', 'Hernandez', 'Lopez', 'sergiohernandezhel@aragon.unam.mx'),
(3, 'Aaron', 'Velasco', 'Agustin', 'aaronvelazcovea@aragon.unam.mx'),
(4, 'Gerardo', 'Gonzalez', 'Hernandez', 'gerardogonzalezgoh@aragon.unam.mx'),
(5, 'Leobardo', 'Hernandez', 'Audelo', 'leoher34@aragon.unam.mx'),
(6, 'Gastaldi', 'Perez', 'Juan', 'juangastaldi9a@aragon.unam.mx'),
(7, 'Elizabeth', 'Juarez', 'Robles', 'elizabethjuarezjur@aragon.unam.mx'),
(8, 'Jorge Iván', 'Campos', 'Bravo', 'jorgecampos47@aragon.unam.mx'),
(9, 'Arturo', 'Rodríguez', 'García', 'arturorodriguez35@aragon.unam.mx'),
(10, 'Rafael', 'Gonzalez', 'Betancourt', 'rafaelgonzalezma2@aragon.unam.mx'),
(11, 'Miguel Angel', 'Sanchez', 'Hernandez', 'miguelsanchezt32@aragon.unam.mx'),
(12, 'Efren', 'lozano', 'Mendez', 'efrenlozanogg2@aragon.unam.mx'),
(13, 'Alejandro', 'Suarez', 'Herrera', 'alejandrosuarezsuh@aragon.unam.mx'),
(14, 'Jorge Arturo', 'Lopez', 'Hernandez', 'jorgelopez91@aragon.unam.mx'),
(15, 'Jonathan', 'Martinez', 'Romero', 'jonathanmartinezky7@aragon.unam.mx'),
(16, 'Cesar Francisco', 'German', 'Rosas', 'cesargermanx9@aragon.unam.mx'),
(17, 'Omar', 'Mendoza', 'Gonzalez', 'omarmendoza564@aragon.unam.mx'),
(18, 'Daniel Fernando', 'Palma', 'Lopez', 'fernandopalmaq6@aragon.unam.mx'),
(19, 'Juan Carlos', 'Camacho', 'Alvarez', 'juancamachocaa@aragon.unam.mx'),
(20, 'Carlos Alberto', 'Parrales', 'Parrales', 'carlosparralesgi2@aragon.unam.mx'),
(21, 'Rafael', 'Gonzales', 'Betancourt', 'rafaglz@aragon.unam.mx'),
(22, 'Dzoara Ivette', 'Anaya', 'Manila', 'dzoaraanayaq5@aragon.unam.mx'),
(23, 'Martin', 'Romero', 'Ugalde', 'martinromerorou@aragon.unam.mx'),
(24, 'Alfredo', 'Mondragon', 'Escobar', 'alfredomondragontg8@aragon.unam.mx'),
(25, 'Robeto MIsael', 'Soberanes', 'Jaime', 'misalesoberanesr8@aragon.unam.mx'),
(26, 'Jose Francisco', 'Salgado', 'Rodriguez', 'franciscosalgadoi2@aragon.unam.mx'),
(27, 'Enrique', 'Garcia', 'Guzman', 'enriquegarcia6u4@aragon.unam.mx'),
(28, 'Maria Angelica', 'Feria', 'Victoria', 'angelicaferiaf6@aragon.unam.mx'),
(29, 'Juan', 'Gastaldi', 'Perez', 'juangastaldi9a@aragon.unam.mx'),
(30, 'Victor Manuel', 'Sanchez', 'Sanchez', 'victorsanchezh0@aragon.unam.mx'),
(31, 'Maria Guadalupe', 'Almanzar', 'Vazquez', 'guadalupealmanzar1@aragon.unam.mx'),
(32, 'Juan German', 'Valenzuela', 'Ramos', 'germanvalenzuelag3@aragon.unam.mx'),
(33, 'Roberto', 'Blanco', 'Bautista', 'robertoblancoir4@aragon.unam.mx'),
(34, 'Blanca Pamela', 'Suarez', 'Camacho', 'blancapamela03@aragon.unam.mx'),
(35, 'Belen Anaid', 'Alba', 'Villa', 'belenalba749@aragon.unam.mx'),
(36, 'Gerardo', 'Gonzalez', 'Hernandez', 'gerardogonzalezgoh@aragon.unam.mx'),
(37, 'Juan', 'Gastaldi', 'Perez', 'juangastaldi9a@aragon.unam.mx'),
(38, 'Juan Manuel', 'Arellano', 'Orozco', 'juanmanuelioro12@aragon.unam.mx'),
(39, 'Esteban', 'Ramirez', 'Lazos', 'estebanralaz03@aragon.unam.mx'),
(40, 'Juan Carlos', 'Ramos', 'Marquez', 'jcramos345@aragon.unam.mx'),
(41, 'Everardo', 'Solis', 'Alcantar', 'esolis768@aragon.unam.mx'),
(42, 'Carlos Alberto', 'Parrales', 'Castaneda', 'caparrales123@aragon.unam.mx'),
(43, 'Luis Armando', 'Vieyra', 'Reboyo', 'lavieyra654@aragon.unam.mx'),
(44, 'Alfredo', 'Mondragon', 'Escobar', 'amondragon321@aragon.unam.mx'),
(45, 'Berenice Itzel', 'Falcon', 'Arellano', 'bfalcon459@aragon.unam.mx'),
(46, 'Ma. Del Pilar', 'Garcia', 'Villanueva', 'pdgarcia777@aragon.unam.mx'),
(47, 'Ernesto', 'Penalosa', 'Romero', 'epenalosa233@aragon.unam.mx'),
(48, 'Jesus Angel', 'Romero', 'Andalon', 'jromero564@aragon.unam.mx'),
(49, 'Joel Alfredo', 'Perez', 'Valdes', 'joperez998@aragon.unam.mx'),
(50, 'Miguel Angel', 'Sanchez', 'Hernandez', 'masanchez123@aragon.unam.mx'),
(51, 'Gabriel', 'Ortiz', 'Cordero', 'gortiz456@aragon.unam.mx'),
(52, 'Alejandro', 'Perez', 'Guzman', 'aperez312@aragon.unam.mx'),
(53, 'Jorge Luis', 'Candelario', 'Alavez', 'jcandelario876@aragon.unam.mx'),
(54, 'Victor Manuel', 'Sanchez', 'Morales', 'vmsanchez257@aragon.unam.mx'),
(55, 'Clara Yahaiera', 'Islas', 'Hernandez', 'cyislas392@aragon.unam.mx'),
(56, 'Matilde', 'Colunga', 'Vazquez', 'mcolunga678@aragon.unam.mx'),
(57, 'Ana Claudia', 'Reyes', 'Cruz', 'acruz321@aragon.unam.mx'),
(58, 'Anaid', 'Alba', 'Villa', 'aavilla485@aragon.unam.mx'),
(59, 'Arturo', 'Rodriguez', 'García', 'arodgriguez637@aragon.unam.mx'),
(60, 'Jorge Ivan', 'Campos', 'Bravo', 'jcampos156@aragon.unam.mx'),
(61, 'Blanca Pamela', 'Aburto', 'Camacho', 'paburto222@aragon.unam.mx'),
(62, 'Salomon', 'Hernandez', 'Galicia', 'shernandez548@aragon.unam.mx'),
(63, 'Efren', 'Guerrero', 'Santamaria', 'eguerrero789@aragon.unam.mx'),
(64, 'Cuauhtemoc', 'Chiapa', 'Monroy', 'cchiapa101@aragon.unam.mx'),
(65, 'Jose Gil', 'Juarez', 'Palma', 'gjuarez123@aragon.unam.mx'),
(66, 'Minerva', 'Segura', 'Rauda', 'msegura775@aragon.unam.mx'),
(67, 'Alma Rosa', 'Gutierrez', 'Castillo', 'rgutierrez393@aragon.unam.mx'),
(68, 'Blanca Estela', 'Cruz', 'Luevano', 'ecruz302@aragon.unam.mx'),
(69, 'Gabriella', 'Piccinelli', 'Bocchi', 'gpiccinelli561@aragon.unam.mx'),
(70, 'Abel', 'Verde', 'Cruz', 'avcrc734@aragon.unam.mx'),
(71, 'Carlos', 'Oliver', 'Morales', 'colivermorales872@aragon.unam.mx'),
(72, 'Fausto', 'Torres', 'Torres', 'ftorres943@aragon.unam.mx'),
(73, 'Martin', 'Ordonez', 'Rosales', 'mordonez678@aragon.unam.mx'),
(74, 'Martha', 'Chapa', 'Plata', 'mchapa299@aragon.unam.mx'),
(75, 'Jesus', 'Hernandez', 'Cabrera', 'jhcabrera512@aragon.unam.mx'),
(76, 'Carlos Fernando', 'Ortega', 'Nava', 'cfo120@aragon.unam.mx'),
(77, 'Rafael', 'Canto', 'Gallo', 'rcanto876@aragon.unam.mx'),
(78, 'Ramon', 'Patino', 'Rodriguez', 'rpatino234@aragon.unam.mx'),
(79, 'Gloria Samantha', 'Pelcastre', 'Ramirez', 'gsapelcastre315@aragon.unam.mx'),
(80, 'Manuel Alejandro', 'Alvarez', 'Soriano', 'malvarez837@aragon.unam.mx'),
(81, 'Moises', 'Cervantes', 'Patino', 'mcervantes102@aragon.unam.mx'),
(82, 'Jaime Roberto Misael', 'Soberanes', 'Jaime', 'jsoberanes550@aragon.unam.mx'),
(83, 'Norma', 'Reyes', 'Tecontero', 'nreyes167@aragon.unam.mx'),
(84, 'Juan Manuel', 'Lopez', 'Carreto', 'jlopez889@aragon.unam.mx'),
(85, 'Jorge Carlos', 'Morales', 'Gonzalez', 'jmorales314@aragon.unam.mx'),
(86, 'Luis Enrique', 'Gonzalez', 'Ayala', 'legonzalez267@aragon.unam.mx'),
(87, 'Jose Luis', 'Ramirez', 'Cruz', 'jramirez408@aragon.unam.mx'),
(88, 'Hector', 'Saldana', 'Aldana', 'hsaldana579@aragon.unam.mx'),
(89, 'Juan Antonio', 'Villanueva', 'Ortega', 'javillanueva123@aragon.unam.mx'),
(90, 'Mariana', 'Verduzco', 'Rodriguez', 'mverduzco542@aragon.unam.mx'),
(91, 'Maria Elena', 'Ortiz', 'Jimenez', 'meortiz320@aragon.unam.mx'),
(92, 'Esteban', 'Arellano', 'Rivera', 'earellano765@aragon.unam.mx'),
(93, 'David Jaime', 'Gonzalez', 'Maxinez', 'djgonzalez849@aragon.unam.mx'),
(94, 'Ricardo Arturo', 'Gutierrez', 'Orozco', 'rggutierrez710@aragon.unam.mx'),
(95, 'Arcelia', 'Bernal', 'Diaz', 'abernal235@aragon.unam.mx'),
(96, 'Maria Gabriela', 'Gonzalez', 'Hernandez', 'mgonzalez541@aragon.unam.mx'),
(97, 'Rodolfo', 'Vazquez', 'Morales', 'rvazquez311@aragon.unam.mx'),
(98, 'Marcelo', 'Perez', 'Medel', 'mperez436@aragon.unam.mx'),
(99, 'Martin', 'Hernandez', 'Hernandez', 'mhhernandez@aragon.unam.mx'),
(100, 'Esteban', 'Ayala', 'Pena', 'eayala298@aragon.unam.mx'),
(101, 'Juan Manuel', 'Hernandez', 'Contreras', 'jhernandez503@aragon.unam.mx'),
(102, 'Jose Antonio', 'Garcia', 'Monroy', 'jgarcia772@aragon.unam.mx'),
(103, 'Jose Manuel', 'Quintero', 'Cervantes', 'jqcervantes657@aragon.unam.mx'),
(104, 'Arturo', 'Ocampo', 'Alvarez', 'aocampo944@aragon.unam.mx'),
(105, 'Alma Lilia', 'Garibay', 'Pedraza', 'algaribay871@aragon.unam.mx'),
(106, 'Antonio Gerardo', 'Perez', 'Munoz', 'aperez401@aragon.unam.mx'),
(107, 'Gerardo', 'Torres', 'Rodriguez', 'gtorres592@aragon.unam.mx'),
(108, 'Ricardo Adolfo', 'Vidal', 'Castro', 'rvidal214@aragon.unam.mx'),
(109, 'Judith', 'Ugalde', 'Lopez', 'jugalde648@aragon.unam.mx'),
(110, 'Felipe De Jesus', 'Gutierrez', 'Lopez', 'fdlopz888@aragon.unam.mx'),
(111, 'Sergio', 'Quiroz', 'Almaraz', 'sqalmaraz549@aragon.unam.mx'),
(112, 'Amilcar Amado', 'Monterrosa', 'Escobar', 'aamonterrosa722@aragon.unam.mx'),
(113, 'Marco Inti', 'Goytia', 'Herrera', 'mgoytia546@aragon.unam.mx'),
(114, 'Benito', 'Zuniga', 'Villegas', 'bzuniga355@aragon.unam.mx'),
(115, 'Jose Daniel', 'Castro', 'Diaz', 'jdcastro@aragon.unam.mx'),
(116, 'Jose Antonio', 'Avila', 'Garcia', 'javilagarcia470@aragon.unam.mx'),
(117, 'Hiram Emmanuel', 'Perez', 'Sanchez', 'hvega711@aragon.unam.mx'),
(118, 'Elio', 'Vega', 'Munguia', 'ggalia302@aragon.unam.mx'),
(119, 'Gilda', 'Galicia', 'Rangel', 'eneria294@aragon.unam.mx'),
(120, 'Erik De Jesus', 'Neria', 'Orozco', 'iflores602@aragon.unam.mx'),
(121, 'Imelda De La Luz', 'Flores', 'Diaz', 'jsrodriguez701@aragon.unam.mx'),
(122, 'Jose Francisco', 'Salgado', 'Rodriguez', 'agreneponce531@aragon.unam.mx'),
(123, 'Alejandro Rene', 'Gonzalez', 'Ponce', 'frcovarrubias589@aragon.unam.mx'),
(124, 'Fernando Roberto', 'Covarrubias', 'Rodriguez', 'bcano799@aragon.unam.mx'),
(125, 'Berenice', 'Cano', 'Santos', 'rvalenzuelalopez710@aragon.unam.mx'),
(126, 'Rodolfo', 'Valenzuela', 'Lopez', 'lhernandezcervantes348@aragon.unam.mx'),
(127, 'Liliana', 'Hernandez', 'Cervantes', 'cescondrillas759@aragon.unam.mx'),
(128, 'Carlos', 'Escondrillas', 'Maya', 'igradaherta236@aragon.unam.mx'),
(129, 'Ivan', 'Grada', 'Huerta', 'epalafox174@aragon.unam.mx'),
(130, 'Edgar', 'Morales', 'Palafox', 'jaguilar986@aragon.unam.mx'),
(131, 'Jose Francisco', 'Aguilar', 'Hernandez', 'cmvelezangel110@aragon.unam.mx'),
(132, 'Carlos Manuel', 'Velez', 'Angel', 'rnavarrodi123@aragon.unam.mx'),
(133, 'Ramon', 'Navarro', 'Diaz', 'mriveropicazo795@aragon.unam.mx'),
(134, 'Mariela Vianey', 'Rivero', 'Picazo', 'rdavilaperez922@aragon.unam.mx'),
(135, 'Rene Adrian', 'Davila', 'Perez', 'renedavilar5@aragon.unam.mx');